<%
    '
    'connection database paths to different database
    '
    workshopPath = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\workshops.mdb"
    surveyPath = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\surveys.mdb"
    conferencePath = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\conferences.mdb"
    transcationPath = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\transactiondb.mdb"
    licensePath = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\licensedb.mdb"
    shippingcalculatorPath = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\ShippingCalculator2010.mdb"
    catalogPath = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\catalog.mdb"
	catalogPathbk = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\catalogbk.mdb"
    weightPath = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\biblio.mdb"
    pagePath = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\PageVersionTracker.mdb"
    crmPath = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\crm.mdb"
    apiUri = "https://secure.chiwater.com/chi/CHI.Data/Repository/"
    apiKey = "pB8.xP5;kM2>jX5<jY4>hX1$eO8)fZ0&"
    '
    'define some globle variable to be used when called
    '
    WireItem = "M301"
    WebTrainingItem = "web workshop"
%>