<%
    '
    'connection database paths to different database
    '
    workshopPath = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\workshops.mdb"
    'surveyPath = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\WorkshopSurveysDB.mdb"
    conferencePath = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\k\conferencesk.mdb"
    transcationPath = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\k\transactiondb.mdb"
    licensePath = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\k\licensedbk.mdb"
    shippingcalculatorPath = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\ShippingCalculator2010.mdb"
    catalogPath = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\k\catalogk.mdb"
    weightPath = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\WWWUsers\LocalUser\chi\computationalhydraulics_com\databases\biblio_weights.mdb"
    '
    'define some globle variable to be used when called
    '
    WireItem = "M301"
    WebTrainingItem = "web workshop"
%>