<%
    '
    'connection database paths to different database
    '
    workshopPath = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\Sharon Deng\Documents\CHI Website\database\workshops.mdb"
    surveyPath = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\Sharon Deng\Documents\CHI Website\database\surveys.mdb"
    conferencePath = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\Sharon Deng\Documents\CHI Website\database\conferences.mdb"
    transcationPath = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\Sharon Deng\Documents\CHI Website\database\transactiondb.mdb"
    licensePath = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\Sharon Deng\Documents\CHI Website\database\licensedb.mdb"
    shippingcalculatorPath = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\Sharon Deng\Documents\CHI Website\database\ShippingCalculator2010.mdb"
    catalogPath = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\Sharon Deng\Documents\CHI Website\database\catalog.mdb"
	catalogPathbk = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\Sharon Deng\Documents\CHI Website\database\catalogbk.mdb"
    weightPath = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\Sharon Deng\Documents\CHI Website\database\biblio.mdb"
    pagePath = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\Sharon Deng\Documents\CHI Website\database\PageVersionTracker.mdb"
    crmPath = "Provider=Microsoft.ACE.OLEDB.12.0;Data C:\Users\Sharon Deng\Documents\CHI Website\database\crm.mdb"
    apiUri = "https://localhost:44340/Repository/"
    apiKey = "pB8.xP5;kM2>jX5<jY4>hX1$eO8)fZ0&"
    '
    'define some globle variable to be used when called
    '
    WireItem = "M301"
    WebTrainingItem = "web workshop"
%>